name: Android CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test secret
        env:
          MY_SECRET: ${{ secrets.SIGNING_PK8 }}
        run: |
          echo "Secret length: ${#MY_SECRET}"
          echo "Secret exists: $([ -n "$MY_SECRET" ] && echo yes || echo no)"
