name: Android CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test env
        env:
          TEST_VAR: hello123
        run: echo "Got: $TEST_VAR"
